include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/zkfp/**
  errors:
    avoid_print: ignore
    use_build_context_synchronously: ignore
    deprecated_member_use: ignore
    invalid_null_aware_operator: ignore
